FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./packages.json ./packages.json
COPY ./turbo.json ./turbo.json

COPY ./apps/wsserver ./apps/wsserver

RUN bun install

CMD [ "bun", "run", "start:ws" ]

