FROM oven/bun:1-alpine

WORKDIR /user/apps

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./packages.json ./packages.json
COPY ./turbo.json ./turbo.json

RUN bun install

COPY ./apps/web ./app/web

RUN bun run build

CMD [ "bun", "run" "start:web"]
