name: Deploy the httpserver

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/dockerfile.httpserver
          push: true
          tags: parther/user-app-http:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 51.20.106.24
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest image
            docker pull parther/user-app-http:${{ github.sha }}

            # Stop and remove the old container if it exists
            docker rm -f user-app-http || true

            # Run the new container
            docker run -d --name user-app-http -p 8080:8080 parther/user-app-http:${{ github.sha }}
